analyzer:
  exclude:
    - build/**
    - lib_backup/**
    - web/**
    - macos/**
    - android/**
    - ios/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
